# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='author',
        ),
    ]
